name : Highway
max_steps : 50
lane_count : 4
snip_trajectory : False
snip_trajectory_window : None
vehicles_count : 5
fps : 2.5
total_timestep : 200000
speed_feedback : True
Fusion:
  T_phi : 1
  crt : 0
  T_min : 0.3
  T_max : 1.5
  slop : 1