name : Pong
max_score : 1
max_steps : 1000
cpu_speed_ratio : 0.5
players_speed_ratio : 0.5
snip_trajectory : True
snip_trajectory_window : 50
fps : 30
total_timestep : 1000000
Fusion:
  T_phi : 0.6
  crt : 0
  T_min : 0.3
  T_max : 5
  slop : 1