_target_: agents.dqn.DQN

Network:
  name : DQN
  input_dim : ???
  action_dim : ???
  fc_hidden_size : [512, 256, 128]
  lr: 1e-4
  gamma : 0.99
  tau : 5e-3
  hard_update : True
  target_update_freequency : 1000
  initial_random_samples : 4000
  epsilon_start : 1.0
  epsilon_end : 0.01
  epsilon_decay : 20000
  batch_size : 100
  buffer_size : 200000
  use_per : False
  learn_after : 10000
  clip_grad_param : 10
  test_episodes : 10
  batch_norm : True
  video_save_path : results
  interaction_data_path : data
Test: 
  checkpoint : model_weights/DQN/2025-09-03_14-45-11_M1LI8T/